quarkus:
  datasource:
    jdbc:
      driver: org.h2.Driver
      url: 'jdbc:h2:mem:'
      transactions: enabled
    password:
    username:
    db-kind: h2
  mybatis:
    xmlconfig:
      enable: true
      path: mybatis-config.xml
    environment: development
  http:
    port: 8086
  application:
    name: quarkus
  native:
    additional-build-args:
      - --report-unsupported-elements-at-runtime
